### ISSUE TITLE
Link ability to transpose radars with radar selection

### ISSUE THREAD

**Issue by lcarlaw** [tjturnage/cloud-radar-server#18]
While the ability to select a radar to transpose to is disabled when a user selects more than 1 radar site from the map and slider bar, they still have the option to select a transpose radar when no original radar is set. 

Disable the transpose div and/or dropdown if no radar has been selected from the map display.

**Comment by tjturnage** [comment]
Circling back to this today (6/11/24) or tomorrow

**Comment by tjturnage** [comment]
Updated radar selection components so there is a "Finalize selections" button that's activated once the length of the radar list equals the quantity of desired radars. The option to transpose displays if both of these values are 1, otherwise there is a message that says the transpose option is not available since selected radars >1
